import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blinguage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <a className={styles.logo}></a>
          <nav className={styles.nav}>
            <ul>
              <li>
                <a href="#" className={styles.hoverUnderlineAnimation}>
                  Courses
                </a>
              </li>
              <li>
                <a href="#" className={styles.hoverUnderlineAnimation}>
                  Why Us
                </a>
              </li>
              <li>
                <a href="#" className={styles.hoverUnderlineAnimation}>
                  Support
                </a>
              </li>
            </ul>
            <button className={styles.buttonPrimary}>Get Started</button>
          </nav>
        </div>

        <section className={styles.hero}>
          <div className={styles.heroText}>
            <h1>Learn Japanese</h1>
            <p>
              Visiting the temples in Kyoto, getting a new job, or making a
              personal connection <br/>
              -no mattter why you want to learn, we have the
              right course for you.
            </p>
            <button className={styles.buttonSecondary}>Get Started</button>
          </div>
        </section>
      </main>
    </>
  );
}
