import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blinguage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/book.png" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/assets/logo.jpg"
          alt="Blinuage"
          width={232}
          height={60}
        />
        <nav className={styles.nav}>
          <ul>
            <li>first</li>
            <li>second</li>
            <li>third</li>
          </ul>
          <button>Button</button>
        </nav>
      </main>
    </div>
  );
}
