import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blinguage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        {/* <Image
            src="/assets/logo.jpg"
            className={styles.logo}
            alt="Blinguage"
            width={232}
            height={60}
          /> */}
        <a className={styles.logo}></a>
        <nav className={styles.nav}>
          <ul>
            <li>
              <a href="#" className={styles.hoverUnderlineAnimation}>
                Courses
              </a>
            </li>
            <li>
              <a href="#" className={styles.hoverUnderlineAnimation}>
                Why Us
              </a>
            </li>
            <li>
              <a href="#" className={styles.hoverUnderlineAnimation}>
                Support
              </a>
            </li>
          </ul>
          <button className={styles.button}>Get Started</button>
        </nav>

        {/* create a hero section */}
        {/* <section className={styles.hero}>
          <div className={styles.heroText}>
            <h1 className={styles.heroTitle}>
              Learn Japanese
            </h1>
            <p className={styles.heroDescription}>
              Blinguage is a language learning platform that helps you learn a
              new language in 3 months.
            </p>
            <button className={styles.button}>Get Started</button>
          </div>
        </section> */}
      </div>
    </>
  );
}
